# Generated by Django 4.0.3 on 2022-03-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('num_ppl', models.IntegerField(default=1)),
                ('num_items', models.IntegerField(default=0)),
                ('invite_code', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'shopping_lists',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(default='Anonymous', max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('user_lists', models.ManyToManyField(db_column='mako', to='shopl_app.list')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
