# Generated by Django 4.0.3 on 2022-04-16 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('num_ppl', models.IntegerField(default=1)),
                ('num_items', models.IntegerField(default=0)),
                ('invite_code', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'shopping_lists',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.FloatField(null=True)),
                ('unit', models.TextField(null=True)),
                ('bought', models.BooleanField(default=False)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopl_app.list')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(default='Anonymous', max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('user_lists', models.ManyToManyField(db_table='user_lists', to='shopl_app.list')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
