# Generated by Django 4.0.3 on 2022-04-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopl_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='called_user',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='calling',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='room_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
