# Generated by Django 4.0.3 on 2022-03-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopl_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_lists',
            field=models.ManyToManyField(db_table='user_lists', to='shopl_app.list'),
        ),
    ]
