# Generated by Django 4.0.3 on 2022-04-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopl_app', '0002_user_called_user_user_calling_user_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='called_user',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
