# Generated by Django 4.0.3 on 2022-03-24 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopl_app', '0002_alter_user_user_lists'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.FloatField(null=True)),
                ('unit', models.TextField(null=True)),
                ('picture_name', models.TextField(null=True)),
                ('bought', models.BooleanField(default=False)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopl_app.list')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
