# Generated by Django 4.0.3 on 2022-04-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopl_app', '0003_alter_user_called_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='called_user',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='room_id',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
