# Generated by Django 4.0.3 on 2022-04-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopl_app', '0004_alter_user_called_user_alter_user_room_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='calling',
        ),
    ]
